### ISSUE TITLE
Offline error when using serverless 2.x

### ISSUE THREAD

**Issue by seb-cr** [comicrelief/serverless-starter-app#47]
I've upgraded my global `serverless` to version 2.9. When testing with `yarn offline`, the first request succeeds, but a subsequent request fails with an ugly stacktrace.

One simple solution is that `serverless` should be installed as a dependency in the starter app. The global `serverless` will fall back to a locally installed version. This will give us a level of control above just the version range in `serverless.yml`.

In the longer term, we might consider upgrading the starter app to the new `serverless` version.

Full output below.

```
$ yarn offline
yarn run v1.22.10
$ sls offline --apiKey api-key
Serverless: DOTENV: Loading environment variables from :
Serverless: Bundling with Webpack...
Time: 469ms
Built at: 11/18/2020 16:10:02
      Asset      Size  Chunks                   Chunk Names
 handler.js   1.8 KiB       0  [emitted]        handler
handler.map  6.15 KiB       0  [emitted] [dev]  handler
Entrypoint handler = handler.js handler.map
[0] external "@comicrelief/lambda-wrapper" 42 bytes {0} [built]
[1] ./handler.js 370 bytes {0} [built]
[2] ./src/Action/Hello.action.js 700 bytes {0} [built]
[3] ./src/Config/Configuration.js 556 bytes {0} [built]
Serverless: Watching for changes...
offline: Starting Offline: dev/eu-west-1.
offline: Offline [http for lambda] listening on http://localhost:3002

   ┌─────────────────────────────────────────────────────────────────────────┐
   │                                                                         │
   │   GET | http://localhost:3001/hello                                     │
   │   POST | http://localhost:3001/2015-03-31/functions/hello/invocations   │
   │                                                                         │
   └─────────────────────────────────────────────────────────────────────────┘

offline: [HTTP] server ready: http://localhost:3001 🚀
offline: 
offline: Enter "rp" to replay the last request

offline: GET /hello (λ: hello)
offline: (λ: hello) RequestId: ckhnlqdd80002axqg4dad26z7  Duration: 289.72 ms  Billed Duration: 300 ms

offline: GET /hello (λ: hello)
offline: Failure: Cannot read property 'defineService' of undefined
TypeError: Cannot read property 'defineService' of undefined
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/aws-sdk/clients/sts.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/aws-sdk/lib/credentials/temporary_credentials.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/aws-sdk/lib/node_loader.js:33:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/aws-sdk/lib/aws.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/@comicrelief/lambda-wrapper/dist/Service/SQS.service.js:10:38)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/@comicrelief/lambda-wrapper/dist/Config/Dependencies.js:12:35)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/node_modules/@comicrelief/lambda-wrapper/dist/index.js:97:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.call (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/external "@comicrelief/lambda-wrapper":1:18)
    at r (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/webpack/bootstrap:19:22)
    at Object.call (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/src/Action/Hello.action.js:1:1)
    at r (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/webpack/bootstrap:19:22)
    at Object.call (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/handler.js:2:1)
    at __webpack_require__ (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/webpack/bootstrap:19:22)
    at /Users/seb3755/repos/github/serverless-starter-app/.webpack/service/webpack:/webpack/bootstrap:83:10
    at Object.<anonymous> (/Users/seb3755/repos/github/serverless-starter-app/.webpack/service/handler.js:1:966)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/Users/seb3755/repos/github/serverless-starter-app/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/seb3755/repos/github/serverless-starter-app/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:80:133
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at InProcessRunner.run (/Users/seb3755/repos/github/serverless-starter-app/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:80:9)
```

**Comment by seb-cr** [comment]
Actually this looks like just a `serverless-offline` issue. Updating from `6.7.0 -> 6.8.0` fixes the problem.
